FROM golang:alpine AS builder

# Set the current working directory inside the container 
WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Get CompileDaemon
RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/migrations .
COPY --from=builder /app/main .
COPY --from=builder /app/.env .

# Expose port 8080 to the outside world
EXPOSE 8080

ENTRYPOINT CompileDaemon -build="go build -o app" -command="./app"