version: '3'
services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: DockerFile
    restart: always
    volumes:
      - ./migrations:/app/migrations
      - ./:/app
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_ROOT_PASSWORD=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  api:
